<?php

/**
 * @file
 * Custom D8 Module.
 */

/**
 * Implements hook_theme().
 */
function d8dev_theme() {
  return [
    'recipe_time_display' => [
      'variables' => [
        'hours' => NULL,
        'fraction' => [
          'top' => NULL,
          'bottom' => NULL,
        ],
      ],
      'template' => 'recipe-time-display',
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function d8dev_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'd8dev/d8dev';
}
